// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Shoot struct {
	ID          int64
	Title       string
	Description string
	Location    string
	Camera      string
	Lens        string
	Status      string
	ShootDate   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
