// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shoots.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShoot = `-- name: CreateShoot :one
INSERT INTO shoots (
    title,
    description,
    location,
    camera,
    lens,
    status,
    shoot_date
) VALUES (
             $1, $2, $3, $4, $5, $6, $7
         )
RETURNING id, title, description, location, camera, lens, status, shoot_date, created_at, updated_at
`

type CreateShootParams struct {
	Title       string
	Description string
	Location    string
	Camera      string
	Lens        string
	Status      string
	ShootDate   pgtype.Timestamptz
}

func (q *Queries) CreateShoot(ctx context.Context, arg CreateShootParams) (Shoot, error) {
	row := q.db.QueryRow(ctx, createShoot,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Camera,
		arg.Lens,
		arg.Status,
		arg.ShootDate,
	)
	var i Shoot
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Camera,
		&i.Lens,
		&i.Status,
		&i.ShootDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteShoot = `-- name: DeleteShoot :exec
DELETE FROM shoots
WHERE id = $1
`

func (q *Queries) DeleteShoot(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteShoot, id)
	return err
}

const getShootByID = `-- name: GetShootByID :one
SELECT id, title, description, location, camera, lens, status, shoot_date, created_at, updated_at
FROM shoots
WHERE id = $1
`

func (q *Queries) GetShootByID(ctx context.Context, id int64) (Shoot, error) {
	row := q.db.QueryRow(ctx, getShootByID, id)
	var i Shoot
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Camera,
		&i.Lens,
		&i.Status,
		&i.ShootDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listShoots = `-- name: ListShoots :many
SELECT id, title, description, location, camera, lens, status, shoot_date, created_at, updated_at
FROM shoots
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListShootsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListShoots(ctx context.Context, arg ListShootsParams) ([]Shoot, error) {
	rows, err := q.db.Query(ctx, listShoots, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shoot
	for rows.Next() {
		var i Shoot
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Camera,
			&i.Lens,
			&i.Status,
			&i.ShootDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShoot = `-- name: UpdateShoot :one
UPDATE shoots
SET
    title = $2,
    description = $3,
    location = $4,
    camera = $5,
    lens = $6,
    status = $7,
    shoot_date = $8,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, location, camera, lens, status, shoot_date, created_at, updated_at
`

type UpdateShootParams struct {
	ID          int64
	Title       string
	Description string
	Location    string
	Camera      string
	Lens        string
	Status      string
	ShootDate   pgtype.Timestamptz
}

func (q *Queries) UpdateShoot(ctx context.Context, arg UpdateShootParams) (Shoot, error) {
	row := q.db.QueryRow(ctx, updateShoot,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Camera,
		arg.Lens,
		arg.Status,
		arg.ShootDate,
	)
	var i Shoot
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Camera,
		&i.Lens,
		&i.Status,
		&i.ShootDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShootStatus = `-- name: UpdateShootStatus :one
UPDATE shoots
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, location, camera, lens, status, shoot_date, created_at, updated_at
`

type UpdateShootStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateShootStatus(ctx context.Context, arg UpdateShootStatusParams) (Shoot, error) {
	row := q.db.QueryRow(ctx, updateShootStatus, arg.ID, arg.Status)
	var i Shoot
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Camera,
		&i.Lens,
		&i.Status,
		&i.ShootDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
